apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-app-service
spec:
  type: LoadBalancer
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000